Minor code improvements
1000000000/CraneFlak pull request #2
Opened 2017-11-24 23:19 UTC by aaronryank

- Magic numbers are bad so I added an enumerator in `interpreter.h` for clarity.
 - Having no blank lines in the source code is also bad so I added some of those too.

2017-11-25 04:16 UTC, Wheatwizard commented
ec9adf4 seems helpful.
However I don't really see the point in ba3a4b6 there is very little on most lines so the addition of new blank lines seems to do nothing at best.

2017-11-25 04:33 UTC, 1000000000 requested changes
Looks pretty good, refactoring the error codes into an enum was definitely a good idea. There are just a few minor formatting things I'd like to see changed before we merge this.

2017-11-25 04:33 UTC, 1000000000 commented on interpreter.c
> +            return interp->status;
This `if` statement should have brackets or it should be on one line.

2017-11-25 04:33 UTC, 1000000000 commented on interpreter.c
> +}
There should be a newline at the end of a file.

2017-11-25 04:33 UTC, 1000000000 commented on interpreter.h
> -
There should be a new line between the standard library includes and the others.

2017-11-25 04:33 UTC, 1000000000 commented on interpreter.h
> +#endif //__interpreter_h_
The lack of space was so that it lined up with the include guard statements at the start of the program.

2017-11-25 04:33 UTC, 1000000000 commented on interpreter.h
> +#endif //__interpreter_h_
There should be a new line at the end of the file.

2017-11-25 17:44 UTC, aaronryank commented
@1000000000 Made the requested changes.

2018-01-09 05:13 UTC, 1000000000 approved these changes

2018-01-09 05:13 UTC, merged